import { CreateDateColumn, DeleteDateColumn, UpdateDateColumn } from "typeorm";

export class AutoGeneratedDate {
  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;

  @DeleteDateColumn()
  deletedAt!: Date;
}
